// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: fixtures/schema.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_fixtures_2fschema_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_fixtures_2fschema_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_fixtures_2fschema_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_fixtures_2fschema_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_fixtures_2fschema_2eproto;
namespace fixtures {
class AdvancedTypes;
struct AdvancedTypesDefaultTypeInternal;
extern AdvancedTypesDefaultTypeInternal _AdvancedTypes_default_instance_;
class AllTypes;
struct AllTypesDefaultTypeInternal;
extern AllTypesDefaultTypeInternal _AllTypes_default_instance_;
class Nested;
struct NestedDefaultTypeInternal;
extern NestedDefaultTypeInternal _Nested_default_instance_;
}  // namespace fixtures
PROTOBUF_NAMESPACE_OPEN
template<> ::fixtures::AdvancedTypes* Arena::CreateMaybeMessage<::fixtures::AdvancedTypes>(Arena*);
template<> ::fixtures::AllTypes* Arena::CreateMaybeMessage<::fixtures::AllTypes>(Arena*);
template<> ::fixtures::Nested* Arena::CreateMaybeMessage<::fixtures::Nested>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace fixtures {

// ===================================================================

class Nested final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:fixtures.Nested) */ {
 public:
  inline Nested() : Nested(nullptr) {}
  ~Nested() override;
  explicit PROTOBUF_CONSTEXPR Nested(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Nested(const Nested& from);
  Nested(Nested&& from) noexcept
    : Nested() {
    *this = ::std::move(from);
  }

  inline Nested& operator=(const Nested& from) {
    CopyFrom(from);
    return *this;
  }
  inline Nested& operator=(Nested&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Nested& default_instance() {
    return *internal_default_instance();
  }
  static inline const Nested* internal_default_instance() {
    return reinterpret_cast<const Nested*>(
               &_Nested_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Nested& a, Nested& b) {
    a.Swap(&b);
  }
  inline void Swap(Nested* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Nested* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Nested* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Nested>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Nested& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Nested& from) {
    Nested::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Nested* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "fixtures.Nested";
  }
  protected:
  explicit Nested(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kNoteFieldNumber = 2,
    kIdFieldNumber = 1,
  };
  // string note = 2;
  void clear_note();
  const std::string& note() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_note(ArgT0&& arg0, ArgT... args);
  std::string* mutable_note();
  PROTOBUF_NODISCARD std::string* release_note();
  void set_allocated_note(std::string* note);
  private:
  const std::string& _internal_note() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_note(const std::string& value);
  std::string* _internal_mutable_note();
  public:

  // int32 id = 1;
  void clear_id();
  int32_t id() const;
  void set_id(int32_t value);
  private:
  int32_t _internal_id() const;
  void _internal_set_id(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:fixtures.Nested)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr note_;
    int32_t id_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_fixtures_2fschema_2eproto;
};
// -------------------------------------------------------------------

class AllTypes final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:fixtures.AllTypes) */ {
 public:
  inline AllTypes() : AllTypes(nullptr) {}
  ~AllTypes() override;
  explicit PROTOBUF_CONSTEXPR AllTypes(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  AllTypes(const AllTypes& from);
  AllTypes(AllTypes&& from) noexcept
    : AllTypes() {
    *this = ::std::move(from);
  }

  inline AllTypes& operator=(const AllTypes& from) {
    CopyFrom(from);
    return *this;
  }
  inline AllTypes& operator=(AllTypes&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const AllTypes& default_instance() {
    return *internal_default_instance();
  }
  static inline const AllTypes* internal_default_instance() {
    return reinterpret_cast<const AllTypes*>(
               &_AllTypes_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(AllTypes& a, AllTypes& b) {
    a.Swap(&b);
  }
  inline void Swap(AllTypes* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(AllTypes* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  AllTypes* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<AllTypes>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const AllTypes& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const AllTypes& from) {
    AllTypes::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(AllTypes* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "fixtures.AllTypes";
  }
  protected:
  explicit AllTypes(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kRepeatedInt32FieldNumber = 17,
    kPackedSint32FieldNumber = 18,
    kStringFFieldNumber = 14,
    kBytesFFieldNumber = 15,
    kNestedFFieldNumber = 16,
    kInt64FFieldNumber = 2,
    kInt32FFieldNumber = 1,
    kUint32FFieldNumber = 3,
    kUint64FFieldNumber = 4,
    kSint64FFieldNumber = 6,
    kSint32FFieldNumber = 5,
    kBoolFFieldNumber = 7,
    kFixed64FFieldNumber = 9,
    kFixed32FFieldNumber = 8,
    kSfixed32FFieldNumber = 10,
    kSfixed64FFieldNumber = 11,
    kDoubleFFieldNumber = 13,
    kFloatFFieldNumber = 12,
  };
  // repeated int32 repeated_int32 = 17 [packed = false];
  int repeated_int32_size() const;
  private:
  int _internal_repeated_int32_size() const;
  public:
  void clear_repeated_int32();
  private:
  int32_t _internal_repeated_int32(int index) const;
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >&
      _internal_repeated_int32() const;
  void _internal_add_repeated_int32(int32_t value);
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >*
      _internal_mutable_repeated_int32();
  public:
  int32_t repeated_int32(int index) const;
  void set_repeated_int32(int index, int32_t value);
  void add_repeated_int32(int32_t value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >&
      repeated_int32() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >*
      mutable_repeated_int32();

  // repeated sint32 packed_sint32 = 18 [packed = true];
  int packed_sint32_size() const;
  private:
  int _internal_packed_sint32_size() const;
  public:
  void clear_packed_sint32();
  private:
  int32_t _internal_packed_sint32(int index) const;
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >&
      _internal_packed_sint32() const;
  void _internal_add_packed_sint32(int32_t value);
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >*
      _internal_mutable_packed_sint32();
  public:
  int32_t packed_sint32(int index) const;
  void set_packed_sint32(int index, int32_t value);
  void add_packed_sint32(int32_t value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >&
      packed_sint32() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >*
      mutable_packed_sint32();

  // string string_f = 14;
  void clear_string_f();
  const std::string& string_f() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_string_f(ArgT0&& arg0, ArgT... args);
  std::string* mutable_string_f();
  PROTOBUF_NODISCARD std::string* release_string_f();
  void set_allocated_string_f(std::string* string_f);
  private:
  const std::string& _internal_string_f() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_string_f(const std::string& value);
  std::string* _internal_mutable_string_f();
  public:

  // bytes bytes_f = 15;
  void clear_bytes_f();
  const std::string& bytes_f() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_bytes_f(ArgT0&& arg0, ArgT... args);
  std::string* mutable_bytes_f();
  PROTOBUF_NODISCARD std::string* release_bytes_f();
  void set_allocated_bytes_f(std::string* bytes_f);
  private:
  const std::string& _internal_bytes_f() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_bytes_f(const std::string& value);
  std::string* _internal_mutable_bytes_f();
  public:

  // .fixtures.Nested nested_f = 16;
  bool has_nested_f() const;
  private:
  bool _internal_has_nested_f() const;
  public:
  void clear_nested_f();
  const ::fixtures::Nested& nested_f() const;
  PROTOBUF_NODISCARD ::fixtures::Nested* release_nested_f();
  ::fixtures::Nested* mutable_nested_f();
  void set_allocated_nested_f(::fixtures::Nested* nested_f);
  private:
  const ::fixtures::Nested& _internal_nested_f() const;
  ::fixtures::Nested* _internal_mutable_nested_f();
  public:
  void unsafe_arena_set_allocated_nested_f(
      ::fixtures::Nested* nested_f);
  ::fixtures::Nested* unsafe_arena_release_nested_f();

  // int64 int64_f = 2;
  void clear_int64_f();
  int64_t int64_f() const;
  void set_int64_f(int64_t value);
  private:
  int64_t _internal_int64_f() const;
  void _internal_set_int64_f(int64_t value);
  public:

  // int32 int32_f = 1;
  void clear_int32_f();
  int32_t int32_f() const;
  void set_int32_f(int32_t value);
  private:
  int32_t _internal_int32_f() const;
  void _internal_set_int32_f(int32_t value);
  public:

  // uint32 uint32_f = 3;
  void clear_uint32_f();
  uint32_t uint32_f() const;
  void set_uint32_f(uint32_t value);
  private:
  uint32_t _internal_uint32_f() const;
  void _internal_set_uint32_f(uint32_t value);
  public:

  // uint64 uint64_f = 4;
  void clear_uint64_f();
  uint64_t uint64_f() const;
  void set_uint64_f(uint64_t value);
  private:
  uint64_t _internal_uint64_f() const;
  void _internal_set_uint64_f(uint64_t value);
  public:

  // sint64 sint64_f = 6;
  void clear_sint64_f();
  int64_t sint64_f() const;
  void set_sint64_f(int64_t value);
  private:
  int64_t _internal_sint64_f() const;
  void _internal_set_sint64_f(int64_t value);
  public:

  // sint32 sint32_f = 5;
  void clear_sint32_f();
  int32_t sint32_f() const;
  void set_sint32_f(int32_t value);
  private:
  int32_t _internal_sint32_f() const;
  void _internal_set_sint32_f(int32_t value);
  public:

  // bool bool_f = 7;
  void clear_bool_f();
  bool bool_f() const;
  void set_bool_f(bool value);
  private:
  bool _internal_bool_f() const;
  void _internal_set_bool_f(bool value);
  public:

  // fixed64 fixed64_f = 9;
  void clear_fixed64_f();
  uint64_t fixed64_f() const;
  void set_fixed64_f(uint64_t value);
  private:
  uint64_t _internal_fixed64_f() const;
  void _internal_set_fixed64_f(uint64_t value);
  public:

  // fixed32 fixed32_f = 8;
  void clear_fixed32_f();
  uint32_t fixed32_f() const;
  void set_fixed32_f(uint32_t value);
  private:
  uint32_t _internal_fixed32_f() const;
  void _internal_set_fixed32_f(uint32_t value);
  public:

  // sfixed32 sfixed32_f = 10;
  void clear_sfixed32_f();
  int32_t sfixed32_f() const;
  void set_sfixed32_f(int32_t value);
  private:
  int32_t _internal_sfixed32_f() const;
  void _internal_set_sfixed32_f(int32_t value);
  public:

  // sfixed64 sfixed64_f = 11;
  void clear_sfixed64_f();
  int64_t sfixed64_f() const;
  void set_sfixed64_f(int64_t value);
  private:
  int64_t _internal_sfixed64_f() const;
  void _internal_set_sfixed64_f(int64_t value);
  public:

  // double double_f = 13;
  void clear_double_f();
  double double_f() const;
  void set_double_f(double value);
  private:
  double _internal_double_f() const;
  void _internal_set_double_f(double value);
  public:

  // float float_f = 12;
  void clear_float_f();
  float float_f() const;
  void set_float_f(float value);
  private:
  float _internal_float_f() const;
  void _internal_set_float_f(float value);
  public:

  // @@protoc_insertion_point(class_scope:fixtures.AllTypes)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t > repeated_int32_;
    ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t > packed_sint32_;
    mutable std::atomic<int> _packed_sint32_cached_byte_size_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr string_f_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr bytes_f_;
    ::fixtures::Nested* nested_f_;
    int64_t int64_f_;
    int32_t int32_f_;
    uint32_t uint32_f_;
    uint64_t uint64_f_;
    int64_t sint64_f_;
    int32_t sint32_f_;
    bool bool_f_;
    uint64_t fixed64_f_;
    uint32_t fixed32_f_;
    int32_t sfixed32_f_;
    int64_t sfixed64_f_;
    double double_f_;
    float float_f_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_fixtures_2fschema_2eproto;
};
// -------------------------------------------------------------------

class AdvancedTypes final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:fixtures.AdvancedTypes) */ {
 public:
  inline AdvancedTypes() : AdvancedTypes(nullptr) {}
  ~AdvancedTypes() override;
  explicit PROTOBUF_CONSTEXPR AdvancedTypes(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  AdvancedTypes(const AdvancedTypes& from);
  AdvancedTypes(AdvancedTypes&& from) noexcept
    : AdvancedTypes() {
    *this = ::std::move(from);
  }

  inline AdvancedTypes& operator=(const AdvancedTypes& from) {
    CopyFrom(from);
    return *this;
  }
  inline AdvancedTypes& operator=(AdvancedTypes&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const AdvancedTypes& default_instance() {
    return *internal_default_instance();
  }
  enum VariantCase {
    kChoiceI32 = 1,
    kChoiceText = 2,
    VARIANT_NOT_SET = 0,
  };

  static inline const AdvancedTypes* internal_default_instance() {
    return reinterpret_cast<const AdvancedTypes*>(
               &_AdvancedTypes_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(AdvancedTypes& a, AdvancedTypes& b) {
    a.Swap(&b);
  }
  inline void Swap(AdvancedTypes* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(AdvancedTypes* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  AdvancedTypes* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<AdvancedTypes>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const AdvancedTypes& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const AdvancedTypes& from) {
    AdvancedTypes::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(AdvancedTypes* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "fixtures.AdvancedTypes";
  }
  protected:
  explicit AdvancedTypes(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kPackedFixed64FieldNumber = 3,
    kChunksFieldNumber = 4,
    kUtf8FieldNumber = 6,
    kBlobFieldNumber = 7,
    kNestedFieldNumber = 8,
    kFlagFieldNumber = 5,
    kChoiceI32FieldNumber = 1,
    kChoiceTextFieldNumber = 2,
  };
  // repeated fixed64 packed_fixed64 = 3 [packed = true];
  int packed_fixed64_size() const;
  private:
  int _internal_packed_fixed64_size() const;
  public:
  void clear_packed_fixed64();
  private:
  uint64_t _internal_packed_fixed64(int index) const;
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< uint64_t >&
      _internal_packed_fixed64() const;
  void _internal_add_packed_fixed64(uint64_t value);
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< uint64_t >*
      _internal_mutable_packed_fixed64();
  public:
  uint64_t packed_fixed64(int index) const;
  void set_packed_fixed64(int index, uint64_t value);
  void add_packed_fixed64(uint64_t value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< uint64_t >&
      packed_fixed64() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< uint64_t >*
      mutable_packed_fixed64();

  // repeated bytes chunks = 4;
  int chunks_size() const;
  private:
  int _internal_chunks_size() const;
  public:
  void clear_chunks();
  const std::string& chunks(int index) const;
  std::string* mutable_chunks(int index);
  void set_chunks(int index, const std::string& value);
  void set_chunks(int index, std::string&& value);
  void set_chunks(int index, const char* value);
  void set_chunks(int index, const void* value, size_t size);
  std::string* add_chunks();
  void add_chunks(const std::string& value);
  void add_chunks(std::string&& value);
  void add_chunks(const char* value);
  void add_chunks(const void* value, size_t size);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>& chunks() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>* mutable_chunks();
  private:
  const std::string& _internal_chunks(int index) const;
  std::string* _internal_add_chunks();
  public:

  // string utf8 = 6;
  void clear_utf8();
  const std::string& utf8() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_utf8(ArgT0&& arg0, ArgT... args);
  std::string* mutable_utf8();
  PROTOBUF_NODISCARD std::string* release_utf8();
  void set_allocated_utf8(std::string* utf8);
  private:
  const std::string& _internal_utf8() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_utf8(const std::string& value);
  std::string* _internal_mutable_utf8();
  public:

  // bytes blob = 7;
  void clear_blob();
  const std::string& blob() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_blob(ArgT0&& arg0, ArgT... args);
  std::string* mutable_blob();
  PROTOBUF_NODISCARD std::string* release_blob();
  void set_allocated_blob(std::string* blob);
  private:
  const std::string& _internal_blob() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_blob(const std::string& value);
  std::string* _internal_mutable_blob();
  public:

  // .fixtures.Nested nested = 8;
  bool has_nested() const;
  private:
  bool _internal_has_nested() const;
  public:
  void clear_nested();
  const ::fixtures::Nested& nested() const;
  PROTOBUF_NODISCARD ::fixtures::Nested* release_nested();
  ::fixtures::Nested* mutable_nested();
  void set_allocated_nested(::fixtures::Nested* nested);
  private:
  const ::fixtures::Nested& _internal_nested() const;
  ::fixtures::Nested* _internal_mutable_nested();
  public:
  void unsafe_arena_set_allocated_nested(
      ::fixtures::Nested* nested);
  ::fixtures::Nested* unsafe_arena_release_nested();

  // bool flag = 5;
  void clear_flag();
  bool flag() const;
  void set_flag(bool value);
  private:
  bool _internal_flag() const;
  void _internal_set_flag(bool value);
  public:

  // int32 choice_i32 = 1;
  bool has_choice_i32() const;
  private:
  bool _internal_has_choice_i32() const;
  public:
  void clear_choice_i32();
  int32_t choice_i32() const;
  void set_choice_i32(int32_t value);
  private:
  int32_t _internal_choice_i32() const;
  void _internal_set_choice_i32(int32_t value);
  public:

  // string choice_text = 2;
  bool has_choice_text() const;
  private:
  bool _internal_has_choice_text() const;
  public:
  void clear_choice_text();
  const std::string& choice_text() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_choice_text(ArgT0&& arg0, ArgT... args);
  std::string* mutable_choice_text();
  PROTOBUF_NODISCARD std::string* release_choice_text();
  void set_allocated_choice_text(std::string* choice_text);
  private:
  const std::string& _internal_choice_text() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_choice_text(const std::string& value);
  std::string* _internal_mutable_choice_text();
  public:

  void clear_variant();
  VariantCase variant_case() const;
  // @@protoc_insertion_point(class_scope:fixtures.AdvancedTypes)
 private:
  class _Internal;
  void set_has_choice_i32();
  void set_has_choice_text();

  inline bool has_variant() const;
  inline void clear_has_variant();

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedField< uint64_t > packed_fixed64_;
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string> chunks_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr utf8_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr blob_;
    ::fixtures::Nested* nested_;
    bool flag_;
    union VariantUnion {
      constexpr VariantUnion() : _constinit_{} {}
        ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized _constinit_;
      int32_t choice_i32_;
      ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr choice_text_;
    } variant_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    uint32_t _oneof_case_[1];

  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_fixtures_2fschema_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Nested

// int32 id = 1;
inline void Nested::clear_id() {
  _impl_.id_ = 0;
}
inline int32_t Nested::_internal_id() const {
  return _impl_.id_;
}
inline int32_t Nested::id() const {
  // @@protoc_insertion_point(field_get:fixtures.Nested.id)
  return _internal_id();
}
inline void Nested::_internal_set_id(int32_t value) {
  
  _impl_.id_ = value;
}
inline void Nested::set_id(int32_t value) {
  _internal_set_id(value);
  // @@protoc_insertion_point(field_set:fixtures.Nested.id)
}

// string note = 2;
inline void Nested::clear_note() {
  _impl_.note_.ClearToEmpty();
}
inline const std::string& Nested::note() const {
  // @@protoc_insertion_point(field_get:fixtures.Nested.note)
  return _internal_note();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Nested::set_note(ArgT0&& arg0, ArgT... args) {
 
 _impl_.note_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:fixtures.Nested.note)
}
inline std::string* Nested::mutable_note() {
  std::string* _s = _internal_mutable_note();
  // @@protoc_insertion_point(field_mutable:fixtures.Nested.note)
  return _s;
}
inline const std::string& Nested::_internal_note() const {
  return _impl_.note_.Get();
}
inline void Nested::_internal_set_note(const std::string& value) {
  
  _impl_.note_.Set(value, GetArenaForAllocation());
}
inline std::string* Nested::_internal_mutable_note() {
  
  return _impl_.note_.Mutable(GetArenaForAllocation());
}
inline std::string* Nested::release_note() {
  // @@protoc_insertion_point(field_release:fixtures.Nested.note)
  return _impl_.note_.Release();
}
inline void Nested::set_allocated_note(std::string* note) {
  if (note != nullptr) {
    
  } else {
    
  }
  _impl_.note_.SetAllocated(note, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.note_.IsDefault()) {
    _impl_.note_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:fixtures.Nested.note)
}

// -------------------------------------------------------------------

// AllTypes

// int32 int32_f = 1;
inline void AllTypes::clear_int32_f() {
  _impl_.int32_f_ = 0;
}
inline int32_t AllTypes::_internal_int32_f() const {
  return _impl_.int32_f_;
}
inline int32_t AllTypes::int32_f() const {
  // @@protoc_insertion_point(field_get:fixtures.AllTypes.int32_f)
  return _internal_int32_f();
}
inline void AllTypes::_internal_set_int32_f(int32_t value) {
  
  _impl_.int32_f_ = value;
}
inline void AllTypes::set_int32_f(int32_t value) {
  _internal_set_int32_f(value);
  // @@protoc_insertion_point(field_set:fixtures.AllTypes.int32_f)
}

// int64 int64_f = 2;
inline void AllTypes::clear_int64_f() {
  _impl_.int64_f_ = int64_t{0};
}
inline int64_t AllTypes::_internal_int64_f() const {
  return _impl_.int64_f_;
}
inline int64_t AllTypes::int64_f() const {
  // @@protoc_insertion_point(field_get:fixtures.AllTypes.int64_f)
  return _internal_int64_f();
}
inline void AllTypes::_internal_set_int64_f(int64_t value) {
  
  _impl_.int64_f_ = value;
}
inline void AllTypes::set_int64_f(int64_t value) {
  _internal_set_int64_f(value);
  // @@protoc_insertion_point(field_set:fixtures.AllTypes.int64_f)
}

// uint32 uint32_f = 3;
inline void AllTypes::clear_uint32_f() {
  _impl_.uint32_f_ = 0u;
}
inline uint32_t AllTypes::_internal_uint32_f() const {
  return _impl_.uint32_f_;
}
inline uint32_t AllTypes::uint32_f() const {
  // @@protoc_insertion_point(field_get:fixtures.AllTypes.uint32_f)
  return _internal_uint32_f();
}
inline void AllTypes::_internal_set_uint32_f(uint32_t value) {
  
  _impl_.uint32_f_ = value;
}
inline void AllTypes::set_uint32_f(uint32_t value) {
  _internal_set_uint32_f(value);
  // @@protoc_insertion_point(field_set:fixtures.AllTypes.uint32_f)
}

// uint64 uint64_f = 4;
inline void AllTypes::clear_uint64_f() {
  _impl_.uint64_f_ = uint64_t{0u};
}
inline uint64_t AllTypes::_internal_uint64_f() const {
  return _impl_.uint64_f_;
}
inline uint64_t AllTypes::uint64_f() const {
  // @@protoc_insertion_point(field_get:fixtures.AllTypes.uint64_f)
  return _internal_uint64_f();
}
inline void AllTypes::_internal_set_uint64_f(uint64_t value) {
  
  _impl_.uint64_f_ = value;
}
inline void AllTypes::set_uint64_f(uint64_t value) {
  _internal_set_uint64_f(value);
  // @@protoc_insertion_point(field_set:fixtures.AllTypes.uint64_f)
}

// sint32 sint32_f = 5;
inline void AllTypes::clear_sint32_f() {
  _impl_.sint32_f_ = 0;
}
inline int32_t AllTypes::_internal_sint32_f() const {
  return _impl_.sint32_f_;
}
inline int32_t AllTypes::sint32_f() const {
  // @@protoc_insertion_point(field_get:fixtures.AllTypes.sint32_f)
  return _internal_sint32_f();
}
inline void AllTypes::_internal_set_sint32_f(int32_t value) {
  
  _impl_.sint32_f_ = value;
}
inline void AllTypes::set_sint32_f(int32_t value) {
  _internal_set_sint32_f(value);
  // @@protoc_insertion_point(field_set:fixtures.AllTypes.sint32_f)
}

// sint64 sint64_f = 6;
inline void AllTypes::clear_sint64_f() {
  _impl_.sint64_f_ = int64_t{0};
}
inline int64_t AllTypes::_internal_sint64_f() const {
  return _impl_.sint64_f_;
}
inline int64_t AllTypes::sint64_f() const {
  // @@protoc_insertion_point(field_get:fixtures.AllTypes.sint64_f)
  return _internal_sint64_f();
}
inline void AllTypes::_internal_set_sint64_f(int64_t value) {
  
  _impl_.sint64_f_ = value;
}
inline void AllTypes::set_sint64_f(int64_t value) {
  _internal_set_sint64_f(value);
  // @@protoc_insertion_point(field_set:fixtures.AllTypes.sint64_f)
}

// bool bool_f = 7;
inline void AllTypes::clear_bool_f() {
  _impl_.bool_f_ = false;
}
inline bool AllTypes::_internal_bool_f() const {
  return _impl_.bool_f_;
}
inline bool AllTypes::bool_f() const {
  // @@protoc_insertion_point(field_get:fixtures.AllTypes.bool_f)
  return _internal_bool_f();
}
inline void AllTypes::_internal_set_bool_f(bool value) {
  
  _impl_.bool_f_ = value;
}
inline void AllTypes::set_bool_f(bool value) {
  _internal_set_bool_f(value);
  // @@protoc_insertion_point(field_set:fixtures.AllTypes.bool_f)
}

// fixed32 fixed32_f = 8;
inline void AllTypes::clear_fixed32_f() {
  _impl_.fixed32_f_ = 0u;
}
inline uint32_t AllTypes::_internal_fixed32_f() const {
  return _impl_.fixed32_f_;
}
inline uint32_t AllTypes::fixed32_f() const {
  // @@protoc_insertion_point(field_get:fixtures.AllTypes.fixed32_f)
  return _internal_fixed32_f();
}
inline void AllTypes::_internal_set_fixed32_f(uint32_t value) {
  
  _impl_.fixed32_f_ = value;
}
inline void AllTypes::set_fixed32_f(uint32_t value) {
  _internal_set_fixed32_f(value);
  // @@protoc_insertion_point(field_set:fixtures.AllTypes.fixed32_f)
}

// fixed64 fixed64_f = 9;
inline void AllTypes::clear_fixed64_f() {
  _impl_.fixed64_f_ = uint64_t{0u};
}
inline uint64_t AllTypes::_internal_fixed64_f() const {
  return _impl_.fixed64_f_;
}
inline uint64_t AllTypes::fixed64_f() const {
  // @@protoc_insertion_point(field_get:fixtures.AllTypes.fixed64_f)
  return _internal_fixed64_f();
}
inline void AllTypes::_internal_set_fixed64_f(uint64_t value) {
  
  _impl_.fixed64_f_ = value;
}
inline void AllTypes::set_fixed64_f(uint64_t value) {
  _internal_set_fixed64_f(value);
  // @@protoc_insertion_point(field_set:fixtures.AllTypes.fixed64_f)
}

// sfixed32 sfixed32_f = 10;
inline void AllTypes::clear_sfixed32_f() {
  _impl_.sfixed32_f_ = 0;
}
inline int32_t AllTypes::_internal_sfixed32_f() const {
  return _impl_.sfixed32_f_;
}
inline int32_t AllTypes::sfixed32_f() const {
  // @@protoc_insertion_point(field_get:fixtures.AllTypes.sfixed32_f)
  return _internal_sfixed32_f();
}
inline void AllTypes::_internal_set_sfixed32_f(int32_t value) {
  
  _impl_.sfixed32_f_ = value;
}
inline void AllTypes::set_sfixed32_f(int32_t value) {
  _internal_set_sfixed32_f(value);
  // @@protoc_insertion_point(field_set:fixtures.AllTypes.sfixed32_f)
}

// sfixed64 sfixed64_f = 11;
inline void AllTypes::clear_sfixed64_f() {
  _impl_.sfixed64_f_ = int64_t{0};
}
inline int64_t AllTypes::_internal_sfixed64_f() const {
  return _impl_.sfixed64_f_;
}
inline int64_t AllTypes::sfixed64_f() const {
  // @@protoc_insertion_point(field_get:fixtures.AllTypes.sfixed64_f)
  return _internal_sfixed64_f();
}
inline void AllTypes::_internal_set_sfixed64_f(int64_t value) {
  
  _impl_.sfixed64_f_ = value;
}
inline void AllTypes::set_sfixed64_f(int64_t value) {
  _internal_set_sfixed64_f(value);
  // @@protoc_insertion_point(field_set:fixtures.AllTypes.sfixed64_f)
}

// float float_f = 12;
inline void AllTypes::clear_float_f() {
  _impl_.float_f_ = 0;
}
inline float AllTypes::_internal_float_f() const {
  return _impl_.float_f_;
}
inline float AllTypes::float_f() const {
  // @@protoc_insertion_point(field_get:fixtures.AllTypes.float_f)
  return _internal_float_f();
}
inline void AllTypes::_internal_set_float_f(float value) {
  
  _impl_.float_f_ = value;
}
inline void AllTypes::set_float_f(float value) {
  _internal_set_float_f(value);
  // @@protoc_insertion_point(field_set:fixtures.AllTypes.float_f)
}

// double double_f = 13;
inline void AllTypes::clear_double_f() {
  _impl_.double_f_ = 0;
}
inline double AllTypes::_internal_double_f() const {
  return _impl_.double_f_;
}
inline double AllTypes::double_f() const {
  // @@protoc_insertion_point(field_get:fixtures.AllTypes.double_f)
  return _internal_double_f();
}
inline void AllTypes::_internal_set_double_f(double value) {
  
  _impl_.double_f_ = value;
}
inline void AllTypes::set_double_f(double value) {
  _internal_set_double_f(value);
  // @@protoc_insertion_point(field_set:fixtures.AllTypes.double_f)
}

// string string_f = 14;
inline void AllTypes::clear_string_f() {
  _impl_.string_f_.ClearToEmpty();
}
inline const std::string& AllTypes::string_f() const {
  // @@protoc_insertion_point(field_get:fixtures.AllTypes.string_f)
  return _internal_string_f();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void AllTypes::set_string_f(ArgT0&& arg0, ArgT... args) {
 
 _impl_.string_f_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:fixtures.AllTypes.string_f)
}
inline std::string* AllTypes::mutable_string_f() {
  std::string* _s = _internal_mutable_string_f();
  // @@protoc_insertion_point(field_mutable:fixtures.AllTypes.string_f)
  return _s;
}
inline const std::string& AllTypes::_internal_string_f() const {
  return _impl_.string_f_.Get();
}
inline void AllTypes::_internal_set_string_f(const std::string& value) {
  
  _impl_.string_f_.Set(value, GetArenaForAllocation());
}
inline std::string* AllTypes::_internal_mutable_string_f() {
  
  return _impl_.string_f_.Mutable(GetArenaForAllocation());
}
inline std::string* AllTypes::release_string_f() {
  // @@protoc_insertion_point(field_release:fixtures.AllTypes.string_f)
  return _impl_.string_f_.Release();
}
inline void AllTypes::set_allocated_string_f(std::string* string_f) {
  if (string_f != nullptr) {
    
  } else {
    
  }
  _impl_.string_f_.SetAllocated(string_f, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.string_f_.IsDefault()) {
    _impl_.string_f_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:fixtures.AllTypes.string_f)
}

// bytes bytes_f = 15;
inline void AllTypes::clear_bytes_f() {
  _impl_.bytes_f_.ClearToEmpty();
}
inline const std::string& AllTypes::bytes_f() const {
  // @@protoc_insertion_point(field_get:fixtures.AllTypes.bytes_f)
  return _internal_bytes_f();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void AllTypes::set_bytes_f(ArgT0&& arg0, ArgT... args) {
 
 _impl_.bytes_f_.SetBytes(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:fixtures.AllTypes.bytes_f)
}
inline std::string* AllTypes::mutable_bytes_f() {
  std::string* _s = _internal_mutable_bytes_f();
  // @@protoc_insertion_point(field_mutable:fixtures.AllTypes.bytes_f)
  return _s;
}
inline const std::string& AllTypes::_internal_bytes_f() const {
  return _impl_.bytes_f_.Get();
}
inline void AllTypes::_internal_set_bytes_f(const std::string& value) {
  
  _impl_.bytes_f_.Set(value, GetArenaForAllocation());
}
inline std::string* AllTypes::_internal_mutable_bytes_f() {
  
  return _impl_.bytes_f_.Mutable(GetArenaForAllocation());
}
inline std::string* AllTypes::release_bytes_f() {
  // @@protoc_insertion_point(field_release:fixtures.AllTypes.bytes_f)
  return _impl_.bytes_f_.Release();
}
inline void AllTypes::set_allocated_bytes_f(std::string* bytes_f) {
  if (bytes_f != nullptr) {
    
  } else {
    
  }
  _impl_.bytes_f_.SetAllocated(bytes_f, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.bytes_f_.IsDefault()) {
    _impl_.bytes_f_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:fixtures.AllTypes.bytes_f)
}

// .fixtures.Nested nested_f = 16;
inline bool AllTypes::_internal_has_nested_f() const {
  return this != internal_default_instance() && _impl_.nested_f_ != nullptr;
}
inline bool AllTypes::has_nested_f() const {
  return _internal_has_nested_f();
}
inline void AllTypes::clear_nested_f() {
  if (GetArenaForAllocation() == nullptr && _impl_.nested_f_ != nullptr) {
    delete _impl_.nested_f_;
  }
  _impl_.nested_f_ = nullptr;
}
inline const ::fixtures::Nested& AllTypes::_internal_nested_f() const {
  const ::fixtures::Nested* p = _impl_.nested_f_;
  return p != nullptr ? *p : reinterpret_cast<const ::fixtures::Nested&>(
      ::fixtures::_Nested_default_instance_);
}
inline const ::fixtures::Nested& AllTypes::nested_f() const {
  // @@protoc_insertion_point(field_get:fixtures.AllTypes.nested_f)
  return _internal_nested_f();
}
inline void AllTypes::unsafe_arena_set_allocated_nested_f(
    ::fixtures::Nested* nested_f) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.nested_f_);
  }
  _impl_.nested_f_ = nested_f;
  if (nested_f) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:fixtures.AllTypes.nested_f)
}
inline ::fixtures::Nested* AllTypes::release_nested_f() {
  
  ::fixtures::Nested* temp = _impl_.nested_f_;
  _impl_.nested_f_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::fixtures::Nested* AllTypes::unsafe_arena_release_nested_f() {
  // @@protoc_insertion_point(field_release:fixtures.AllTypes.nested_f)
  
  ::fixtures::Nested* temp = _impl_.nested_f_;
  _impl_.nested_f_ = nullptr;
  return temp;
}
inline ::fixtures::Nested* AllTypes::_internal_mutable_nested_f() {
  
  if (_impl_.nested_f_ == nullptr) {
    auto* p = CreateMaybeMessage<::fixtures::Nested>(GetArenaForAllocation());
    _impl_.nested_f_ = p;
  }
  return _impl_.nested_f_;
}
inline ::fixtures::Nested* AllTypes::mutable_nested_f() {
  ::fixtures::Nested* _msg = _internal_mutable_nested_f();
  // @@protoc_insertion_point(field_mutable:fixtures.AllTypes.nested_f)
  return _msg;
}
inline void AllTypes::set_allocated_nested_f(::fixtures::Nested* nested_f) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete _impl_.nested_f_;
  }
  if (nested_f) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(nested_f);
    if (message_arena != submessage_arena) {
      nested_f = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, nested_f, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.nested_f_ = nested_f;
  // @@protoc_insertion_point(field_set_allocated:fixtures.AllTypes.nested_f)
}

// repeated int32 repeated_int32 = 17 [packed = false];
inline int AllTypes::_internal_repeated_int32_size() const {
  return _impl_.repeated_int32_.size();
}
inline int AllTypes::repeated_int32_size() const {
  return _internal_repeated_int32_size();
}
inline void AllTypes::clear_repeated_int32() {
  _impl_.repeated_int32_.Clear();
}
inline int32_t AllTypes::_internal_repeated_int32(int index) const {
  return _impl_.repeated_int32_.Get(index);
}
inline int32_t AllTypes::repeated_int32(int index) const {
  // @@protoc_insertion_point(field_get:fixtures.AllTypes.repeated_int32)
  return _internal_repeated_int32(index);
}
inline void AllTypes::set_repeated_int32(int index, int32_t value) {
  _impl_.repeated_int32_.Set(index, value);
  // @@protoc_insertion_point(field_set:fixtures.AllTypes.repeated_int32)
}
inline void AllTypes::_internal_add_repeated_int32(int32_t value) {
  _impl_.repeated_int32_.Add(value);
}
inline void AllTypes::add_repeated_int32(int32_t value) {
  _internal_add_repeated_int32(value);
  // @@protoc_insertion_point(field_add:fixtures.AllTypes.repeated_int32)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >&
AllTypes::_internal_repeated_int32() const {
  return _impl_.repeated_int32_;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >&
AllTypes::repeated_int32() const {
  // @@protoc_insertion_point(field_list:fixtures.AllTypes.repeated_int32)
  return _internal_repeated_int32();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >*
AllTypes::_internal_mutable_repeated_int32() {
  return &_impl_.repeated_int32_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >*
AllTypes::mutable_repeated_int32() {
  // @@protoc_insertion_point(field_mutable_list:fixtures.AllTypes.repeated_int32)
  return _internal_mutable_repeated_int32();
}

// repeated sint32 packed_sint32 = 18 [packed = true];
inline int AllTypes::_internal_packed_sint32_size() const {
  return _impl_.packed_sint32_.size();
}
inline int AllTypes::packed_sint32_size() const {
  return _internal_packed_sint32_size();
}
inline void AllTypes::clear_packed_sint32() {
  _impl_.packed_sint32_.Clear();
}
inline int32_t AllTypes::_internal_packed_sint32(int index) const {
  return _impl_.packed_sint32_.Get(index);
}
inline int32_t AllTypes::packed_sint32(int index) const {
  // @@protoc_insertion_point(field_get:fixtures.AllTypes.packed_sint32)
  return _internal_packed_sint32(index);
}
inline void AllTypes::set_packed_sint32(int index, int32_t value) {
  _impl_.packed_sint32_.Set(index, value);
  // @@protoc_insertion_point(field_set:fixtures.AllTypes.packed_sint32)
}
inline void AllTypes::_internal_add_packed_sint32(int32_t value) {
  _impl_.packed_sint32_.Add(value);
}
inline void AllTypes::add_packed_sint32(int32_t value) {
  _internal_add_packed_sint32(value);
  // @@protoc_insertion_point(field_add:fixtures.AllTypes.packed_sint32)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >&
AllTypes::_internal_packed_sint32() const {
  return _impl_.packed_sint32_;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >&
AllTypes::packed_sint32() const {
  // @@protoc_insertion_point(field_list:fixtures.AllTypes.packed_sint32)
  return _internal_packed_sint32();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >*
AllTypes::_internal_mutable_packed_sint32() {
  return &_impl_.packed_sint32_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >*
AllTypes::mutable_packed_sint32() {
  // @@protoc_insertion_point(field_mutable_list:fixtures.AllTypes.packed_sint32)
  return _internal_mutable_packed_sint32();
}

// -------------------------------------------------------------------

// AdvancedTypes

// int32 choice_i32 = 1;
inline bool AdvancedTypes::_internal_has_choice_i32() const {
  return variant_case() == kChoiceI32;
}
inline bool AdvancedTypes::has_choice_i32() const {
  return _internal_has_choice_i32();
}
inline void AdvancedTypes::set_has_choice_i32() {
  _impl_._oneof_case_[0] = kChoiceI32;
}
inline void AdvancedTypes::clear_choice_i32() {
  if (_internal_has_choice_i32()) {
    _impl_.variant_.choice_i32_ = 0;
    clear_has_variant();
  }
}
inline int32_t AdvancedTypes::_internal_choice_i32() const {
  if (_internal_has_choice_i32()) {
    return _impl_.variant_.choice_i32_;
  }
  return 0;
}
inline void AdvancedTypes::_internal_set_choice_i32(int32_t value) {
  if (!_internal_has_choice_i32()) {
    clear_variant();
    set_has_choice_i32();
  }
  _impl_.variant_.choice_i32_ = value;
}
inline int32_t AdvancedTypes::choice_i32() const {
  // @@protoc_insertion_point(field_get:fixtures.AdvancedTypes.choice_i32)
  return _internal_choice_i32();
}
inline void AdvancedTypes::set_choice_i32(int32_t value) {
  _internal_set_choice_i32(value);
  // @@protoc_insertion_point(field_set:fixtures.AdvancedTypes.choice_i32)
}

// string choice_text = 2;
inline bool AdvancedTypes::_internal_has_choice_text() const {
  return variant_case() == kChoiceText;
}
inline bool AdvancedTypes::has_choice_text() const {
  return _internal_has_choice_text();
}
inline void AdvancedTypes::set_has_choice_text() {
  _impl_._oneof_case_[0] = kChoiceText;
}
inline void AdvancedTypes::clear_choice_text() {
  if (_internal_has_choice_text()) {
    _impl_.variant_.choice_text_.Destroy();
    clear_has_variant();
  }
}
inline const std::string& AdvancedTypes::choice_text() const {
  // @@protoc_insertion_point(field_get:fixtures.AdvancedTypes.choice_text)
  return _internal_choice_text();
}
template <typename ArgT0, typename... ArgT>
inline void AdvancedTypes::set_choice_text(ArgT0&& arg0, ArgT... args) {
  if (!_internal_has_choice_text()) {
    clear_variant();
    set_has_choice_text();
    _impl_.variant_.choice_text_.InitDefault();
  }
  _impl_.variant_.choice_text_.Set( static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:fixtures.AdvancedTypes.choice_text)
}
inline std::string* AdvancedTypes::mutable_choice_text() {
  std::string* _s = _internal_mutable_choice_text();
  // @@protoc_insertion_point(field_mutable:fixtures.AdvancedTypes.choice_text)
  return _s;
}
inline const std::string& AdvancedTypes::_internal_choice_text() const {
  if (_internal_has_choice_text()) {
    return _impl_.variant_.choice_text_.Get();
  }
  return ::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited();
}
inline void AdvancedTypes::_internal_set_choice_text(const std::string& value) {
  if (!_internal_has_choice_text()) {
    clear_variant();
    set_has_choice_text();
    _impl_.variant_.choice_text_.InitDefault();
  }
  _impl_.variant_.choice_text_.Set(value, GetArenaForAllocation());
}
inline std::string* AdvancedTypes::_internal_mutable_choice_text() {
  if (!_internal_has_choice_text()) {
    clear_variant();
    set_has_choice_text();
    _impl_.variant_.choice_text_.InitDefault();
  }
  return _impl_.variant_.choice_text_.Mutable(      GetArenaForAllocation());
}
inline std::string* AdvancedTypes::release_choice_text() {
  // @@protoc_insertion_point(field_release:fixtures.AdvancedTypes.choice_text)
  if (_internal_has_choice_text()) {
    clear_has_variant();
    return _impl_.variant_.choice_text_.Release();
  } else {
    return nullptr;
  }
}
inline void AdvancedTypes::set_allocated_choice_text(std::string* choice_text) {
  if (has_variant()) {
    clear_variant();
  }
  if (choice_text != nullptr) {
    set_has_choice_text();
    _impl_.variant_.choice_text_.InitAllocated(choice_text, GetArenaForAllocation());
  }
  // @@protoc_insertion_point(field_set_allocated:fixtures.AdvancedTypes.choice_text)
}

// repeated fixed64 packed_fixed64 = 3 [packed = true];
inline int AdvancedTypes::_internal_packed_fixed64_size() const {
  return _impl_.packed_fixed64_.size();
}
inline int AdvancedTypes::packed_fixed64_size() const {
  return _internal_packed_fixed64_size();
}
inline void AdvancedTypes::clear_packed_fixed64() {
  _impl_.packed_fixed64_.Clear();
}
inline uint64_t AdvancedTypes::_internal_packed_fixed64(int index) const {
  return _impl_.packed_fixed64_.Get(index);
}
inline uint64_t AdvancedTypes::packed_fixed64(int index) const {
  // @@protoc_insertion_point(field_get:fixtures.AdvancedTypes.packed_fixed64)
  return _internal_packed_fixed64(index);
}
inline void AdvancedTypes::set_packed_fixed64(int index, uint64_t value) {
  _impl_.packed_fixed64_.Set(index, value);
  // @@protoc_insertion_point(field_set:fixtures.AdvancedTypes.packed_fixed64)
}
inline void AdvancedTypes::_internal_add_packed_fixed64(uint64_t value) {
  _impl_.packed_fixed64_.Add(value);
}
inline void AdvancedTypes::add_packed_fixed64(uint64_t value) {
  _internal_add_packed_fixed64(value);
  // @@protoc_insertion_point(field_add:fixtures.AdvancedTypes.packed_fixed64)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< uint64_t >&
AdvancedTypes::_internal_packed_fixed64() const {
  return _impl_.packed_fixed64_;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< uint64_t >&
AdvancedTypes::packed_fixed64() const {
  // @@protoc_insertion_point(field_list:fixtures.AdvancedTypes.packed_fixed64)
  return _internal_packed_fixed64();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< uint64_t >*
AdvancedTypes::_internal_mutable_packed_fixed64() {
  return &_impl_.packed_fixed64_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< uint64_t >*
AdvancedTypes::mutable_packed_fixed64() {
  // @@protoc_insertion_point(field_mutable_list:fixtures.AdvancedTypes.packed_fixed64)
  return _internal_mutable_packed_fixed64();
}

// repeated bytes chunks = 4;
inline int AdvancedTypes::_internal_chunks_size() const {
  return _impl_.chunks_.size();
}
inline int AdvancedTypes::chunks_size() const {
  return _internal_chunks_size();
}
inline void AdvancedTypes::clear_chunks() {
  _impl_.chunks_.Clear();
}
inline std::string* AdvancedTypes::add_chunks() {
  std::string* _s = _internal_add_chunks();
  // @@protoc_insertion_point(field_add_mutable:fixtures.AdvancedTypes.chunks)
  return _s;
}
inline const std::string& AdvancedTypes::_internal_chunks(int index) const {
  return _impl_.chunks_.Get(index);
}
inline const std::string& AdvancedTypes::chunks(int index) const {
  // @@protoc_insertion_point(field_get:fixtures.AdvancedTypes.chunks)
  return _internal_chunks(index);
}
inline std::string* AdvancedTypes::mutable_chunks(int index) {
  // @@protoc_insertion_point(field_mutable:fixtures.AdvancedTypes.chunks)
  return _impl_.chunks_.Mutable(index);
}
inline void AdvancedTypes::set_chunks(int index, const std::string& value) {
  _impl_.chunks_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set:fixtures.AdvancedTypes.chunks)
}
inline void AdvancedTypes::set_chunks(int index, std::string&& value) {
  _impl_.chunks_.Mutable(index)->assign(std::move(value));
  // @@protoc_insertion_point(field_set:fixtures.AdvancedTypes.chunks)
}
inline void AdvancedTypes::set_chunks(int index, const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _impl_.chunks_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:fixtures.AdvancedTypes.chunks)
}
inline void AdvancedTypes::set_chunks(int index, const void* value, size_t size) {
  _impl_.chunks_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:fixtures.AdvancedTypes.chunks)
}
inline std::string* AdvancedTypes::_internal_add_chunks() {
  return _impl_.chunks_.Add();
}
inline void AdvancedTypes::add_chunks(const std::string& value) {
  _impl_.chunks_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:fixtures.AdvancedTypes.chunks)
}
inline void AdvancedTypes::add_chunks(std::string&& value) {
  _impl_.chunks_.Add(std::move(value));
  // @@protoc_insertion_point(field_add:fixtures.AdvancedTypes.chunks)
}
inline void AdvancedTypes::add_chunks(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _impl_.chunks_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:fixtures.AdvancedTypes.chunks)
}
inline void AdvancedTypes::add_chunks(const void* value, size_t size) {
  _impl_.chunks_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:fixtures.AdvancedTypes.chunks)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>&
AdvancedTypes::chunks() const {
  // @@protoc_insertion_point(field_list:fixtures.AdvancedTypes.chunks)
  return _impl_.chunks_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>*
AdvancedTypes::mutable_chunks() {
  // @@protoc_insertion_point(field_mutable_list:fixtures.AdvancedTypes.chunks)
  return &_impl_.chunks_;
}

// bool flag = 5;
inline void AdvancedTypes::clear_flag() {
  _impl_.flag_ = false;
}
inline bool AdvancedTypes::_internal_flag() const {
  return _impl_.flag_;
}
inline bool AdvancedTypes::flag() const {
  // @@protoc_insertion_point(field_get:fixtures.AdvancedTypes.flag)
  return _internal_flag();
}
inline void AdvancedTypes::_internal_set_flag(bool value) {
  
  _impl_.flag_ = value;
}
inline void AdvancedTypes::set_flag(bool value) {
  _internal_set_flag(value);
  // @@protoc_insertion_point(field_set:fixtures.AdvancedTypes.flag)
}

// string utf8 = 6;
inline void AdvancedTypes::clear_utf8() {
  _impl_.utf8_.ClearToEmpty();
}
inline const std::string& AdvancedTypes::utf8() const {
  // @@protoc_insertion_point(field_get:fixtures.AdvancedTypes.utf8)
  return _internal_utf8();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void AdvancedTypes::set_utf8(ArgT0&& arg0, ArgT... args) {
 
 _impl_.utf8_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:fixtures.AdvancedTypes.utf8)
}
inline std::string* AdvancedTypes::mutable_utf8() {
  std::string* _s = _internal_mutable_utf8();
  // @@protoc_insertion_point(field_mutable:fixtures.AdvancedTypes.utf8)
  return _s;
}
inline const std::string& AdvancedTypes::_internal_utf8() const {
  return _impl_.utf8_.Get();
}
inline void AdvancedTypes::_internal_set_utf8(const std::string& value) {
  
  _impl_.utf8_.Set(value, GetArenaForAllocation());
}
inline std::string* AdvancedTypes::_internal_mutable_utf8() {
  
  return _impl_.utf8_.Mutable(GetArenaForAllocation());
}
inline std::string* AdvancedTypes::release_utf8() {
  // @@protoc_insertion_point(field_release:fixtures.AdvancedTypes.utf8)
  return _impl_.utf8_.Release();
}
inline void AdvancedTypes::set_allocated_utf8(std::string* utf8) {
  if (utf8 != nullptr) {
    
  } else {
    
  }
  _impl_.utf8_.SetAllocated(utf8, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.utf8_.IsDefault()) {
    _impl_.utf8_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:fixtures.AdvancedTypes.utf8)
}

// bytes blob = 7;
inline void AdvancedTypes::clear_blob() {
  _impl_.blob_.ClearToEmpty();
}
inline const std::string& AdvancedTypes::blob() const {
  // @@protoc_insertion_point(field_get:fixtures.AdvancedTypes.blob)
  return _internal_blob();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void AdvancedTypes::set_blob(ArgT0&& arg0, ArgT... args) {
 
 _impl_.blob_.SetBytes(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:fixtures.AdvancedTypes.blob)
}
inline std::string* AdvancedTypes::mutable_blob() {
  std::string* _s = _internal_mutable_blob();
  // @@protoc_insertion_point(field_mutable:fixtures.AdvancedTypes.blob)
  return _s;
}
inline const std::string& AdvancedTypes::_internal_blob() const {
  return _impl_.blob_.Get();
}
inline void AdvancedTypes::_internal_set_blob(const std::string& value) {
  
  _impl_.blob_.Set(value, GetArenaForAllocation());
}
inline std::string* AdvancedTypes::_internal_mutable_blob() {
  
  return _impl_.blob_.Mutable(GetArenaForAllocation());
}
inline std::string* AdvancedTypes::release_blob() {
  // @@protoc_insertion_point(field_release:fixtures.AdvancedTypes.blob)
  return _impl_.blob_.Release();
}
inline void AdvancedTypes::set_allocated_blob(std::string* blob) {
  if (blob != nullptr) {
    
  } else {
    
  }
  _impl_.blob_.SetAllocated(blob, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.blob_.IsDefault()) {
    _impl_.blob_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:fixtures.AdvancedTypes.blob)
}

// .fixtures.Nested nested = 8;
inline bool AdvancedTypes::_internal_has_nested() const {
  return this != internal_default_instance() && _impl_.nested_ != nullptr;
}
inline bool AdvancedTypes::has_nested() const {
  return _internal_has_nested();
}
inline void AdvancedTypes::clear_nested() {
  if (GetArenaForAllocation() == nullptr && _impl_.nested_ != nullptr) {
    delete _impl_.nested_;
  }
  _impl_.nested_ = nullptr;
}
inline const ::fixtures::Nested& AdvancedTypes::_internal_nested() const {
  const ::fixtures::Nested* p = _impl_.nested_;
  return p != nullptr ? *p : reinterpret_cast<const ::fixtures::Nested&>(
      ::fixtures::_Nested_default_instance_);
}
inline const ::fixtures::Nested& AdvancedTypes::nested() const {
  // @@protoc_insertion_point(field_get:fixtures.AdvancedTypes.nested)
  return _internal_nested();
}
inline void AdvancedTypes::unsafe_arena_set_allocated_nested(
    ::fixtures::Nested* nested) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.nested_);
  }
  _impl_.nested_ = nested;
  if (nested) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:fixtures.AdvancedTypes.nested)
}
inline ::fixtures::Nested* AdvancedTypes::release_nested() {
  
  ::fixtures::Nested* temp = _impl_.nested_;
  _impl_.nested_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::fixtures::Nested* AdvancedTypes::unsafe_arena_release_nested() {
  // @@protoc_insertion_point(field_release:fixtures.AdvancedTypes.nested)
  
  ::fixtures::Nested* temp = _impl_.nested_;
  _impl_.nested_ = nullptr;
  return temp;
}
inline ::fixtures::Nested* AdvancedTypes::_internal_mutable_nested() {
  
  if (_impl_.nested_ == nullptr) {
    auto* p = CreateMaybeMessage<::fixtures::Nested>(GetArenaForAllocation());
    _impl_.nested_ = p;
  }
  return _impl_.nested_;
}
inline ::fixtures::Nested* AdvancedTypes::mutable_nested() {
  ::fixtures::Nested* _msg = _internal_mutable_nested();
  // @@protoc_insertion_point(field_mutable:fixtures.AdvancedTypes.nested)
  return _msg;
}
inline void AdvancedTypes::set_allocated_nested(::fixtures::Nested* nested) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete _impl_.nested_;
  }
  if (nested) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(nested);
    if (message_arena != submessage_arena) {
      nested = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, nested, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.nested_ = nested;
  // @@protoc_insertion_point(field_set_allocated:fixtures.AdvancedTypes.nested)
}

inline bool AdvancedTypes::has_variant() const {
  return variant_case() != VARIANT_NOT_SET;
}
inline void AdvancedTypes::clear_has_variant() {
  _impl_._oneof_case_[0] = VARIANT_NOT_SET;
}
inline AdvancedTypes::VariantCase AdvancedTypes::variant_case() const {
  return AdvancedTypes::VariantCase(_impl_._oneof_case_[0]);
}
#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace fixtures

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_fixtures_2fschema_2eproto
