// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: fixtures/schema.proto

#include "fixtures/schema.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace fixtures {
PROTOBUF_CONSTEXPR Nested::Nested(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.note_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.id_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct NestedDefaultTypeInternal {
  PROTOBUF_CONSTEXPR NestedDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~NestedDefaultTypeInternal() {}
  union {
    Nested _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 NestedDefaultTypeInternal _Nested_default_instance_;
PROTOBUF_CONSTEXPR AllTypes::AllTypes(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.repeated_int32_)*/{}
  , /*decltype(_impl_.packed_sint32_)*/{}
  , /*decltype(_impl_._packed_sint32_cached_byte_size_)*/{0}
  , /*decltype(_impl_.string_f_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.bytes_f_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.nested_f_)*/nullptr
  , /*decltype(_impl_.int64_f_)*/int64_t{0}
  , /*decltype(_impl_.int32_f_)*/0
  , /*decltype(_impl_.uint32_f_)*/0u
  , /*decltype(_impl_.uint64_f_)*/uint64_t{0u}
  , /*decltype(_impl_.sint64_f_)*/int64_t{0}
  , /*decltype(_impl_.sint32_f_)*/0
  , /*decltype(_impl_.bool_f_)*/false
  , /*decltype(_impl_.fixed64_f_)*/uint64_t{0u}
  , /*decltype(_impl_.fixed32_f_)*/0u
  , /*decltype(_impl_.sfixed32_f_)*/0
  , /*decltype(_impl_.sfixed64_f_)*/int64_t{0}
  , /*decltype(_impl_.double_f_)*/0
  , /*decltype(_impl_.float_f_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct AllTypesDefaultTypeInternal {
  PROTOBUF_CONSTEXPR AllTypesDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~AllTypesDefaultTypeInternal() {}
  union {
    AllTypes _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 AllTypesDefaultTypeInternal _AllTypes_default_instance_;
PROTOBUF_CONSTEXPR AdvancedTypes::AdvancedTypes(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.packed_fixed64_)*/{}
  , /*decltype(_impl_.chunks_)*/{}
  , /*decltype(_impl_.utf8_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.blob_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.nested_)*/nullptr
  , /*decltype(_impl_.flag_)*/false
  , /*decltype(_impl_.variant_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}
  , /*decltype(_impl_._oneof_case_)*/{}} {}
struct AdvancedTypesDefaultTypeInternal {
  PROTOBUF_CONSTEXPR AdvancedTypesDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~AdvancedTypesDefaultTypeInternal() {}
  union {
    AdvancedTypes _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 AdvancedTypesDefaultTypeInternal _AdvancedTypes_default_instance_;
}  // namespace fixtures
static ::_pb::Metadata file_level_metadata_fixtures_2fschema_2eproto[3];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_fixtures_2fschema_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_fixtures_2fschema_2eproto = nullptr;

const uint32_t TableStruct_fixtures_2fschema_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::fixtures::Nested, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::fixtures::Nested, _impl_.id_),
  PROTOBUF_FIELD_OFFSET(::fixtures::Nested, _impl_.note_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::fixtures::AllTypes, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::fixtures::AllTypes, _impl_.int32_f_),
  PROTOBUF_FIELD_OFFSET(::fixtures::AllTypes, _impl_.int64_f_),
  PROTOBUF_FIELD_OFFSET(::fixtures::AllTypes, _impl_.uint32_f_),
  PROTOBUF_FIELD_OFFSET(::fixtures::AllTypes, _impl_.uint64_f_),
  PROTOBUF_FIELD_OFFSET(::fixtures::AllTypes, _impl_.sint32_f_),
  PROTOBUF_FIELD_OFFSET(::fixtures::AllTypes, _impl_.sint64_f_),
  PROTOBUF_FIELD_OFFSET(::fixtures::AllTypes, _impl_.bool_f_),
  PROTOBUF_FIELD_OFFSET(::fixtures::AllTypes, _impl_.fixed32_f_),
  PROTOBUF_FIELD_OFFSET(::fixtures::AllTypes, _impl_.fixed64_f_),
  PROTOBUF_FIELD_OFFSET(::fixtures::AllTypes, _impl_.sfixed32_f_),
  PROTOBUF_FIELD_OFFSET(::fixtures::AllTypes, _impl_.sfixed64_f_),
  PROTOBUF_FIELD_OFFSET(::fixtures::AllTypes, _impl_.float_f_),
  PROTOBUF_FIELD_OFFSET(::fixtures::AllTypes, _impl_.double_f_),
  PROTOBUF_FIELD_OFFSET(::fixtures::AllTypes, _impl_.string_f_),
  PROTOBUF_FIELD_OFFSET(::fixtures::AllTypes, _impl_.bytes_f_),
  PROTOBUF_FIELD_OFFSET(::fixtures::AllTypes, _impl_.nested_f_),
  PROTOBUF_FIELD_OFFSET(::fixtures::AllTypes, _impl_.repeated_int32_),
  PROTOBUF_FIELD_OFFSET(::fixtures::AllTypes, _impl_.packed_sint32_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::fixtures::AdvancedTypes, _internal_metadata_),
  ~0u,  // no _extensions_
  PROTOBUF_FIELD_OFFSET(::fixtures::AdvancedTypes, _impl_._oneof_case_[0]),
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  ::_pbi::kInvalidFieldOffsetTag,
  ::_pbi::kInvalidFieldOffsetTag,
  PROTOBUF_FIELD_OFFSET(::fixtures::AdvancedTypes, _impl_.packed_fixed64_),
  PROTOBUF_FIELD_OFFSET(::fixtures::AdvancedTypes, _impl_.chunks_),
  PROTOBUF_FIELD_OFFSET(::fixtures::AdvancedTypes, _impl_.flag_),
  PROTOBUF_FIELD_OFFSET(::fixtures::AdvancedTypes, _impl_.utf8_),
  PROTOBUF_FIELD_OFFSET(::fixtures::AdvancedTypes, _impl_.blob_),
  PROTOBUF_FIELD_OFFSET(::fixtures::AdvancedTypes, _impl_.nested_),
  PROTOBUF_FIELD_OFFSET(::fixtures::AdvancedTypes, _impl_.variant_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::fixtures::Nested)},
  { 8, -1, -1, sizeof(::fixtures::AllTypes)},
  { 32, -1, -1, sizeof(::fixtures::AdvancedTypes)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::fixtures::_Nested_default_instance_._instance,
  &::fixtures::_AllTypes_default_instance_._instance,
  &::fixtures::_AdvancedTypes_default_instance_._instance,
};

const char descriptor_table_protodef_fixtures_2fschema_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\025fixtures/schema.proto\022\010fixtures\"\"\n\006Nes"
  "ted\022\n\n\002id\030\001 \001(\005\022\014\n\004note\030\002 \001(\t\"\363\002\n\010AllTyp"
  "es\022\017\n\007int32_f\030\001 \001(\005\022\017\n\007int64_f\030\002 \001(\003\022\020\n\010"
  "uint32_f\030\003 \001(\r\022\020\n\010uint64_f\030\004 \001(\004\022\020\n\010sint"
  "32_f\030\005 \001(\021\022\020\n\010sint64_f\030\006 \001(\022\022\016\n\006bool_f\030\007"
  " \001(\010\022\021\n\tfixed32_f\030\010 \001(\007\022\021\n\tfixed64_f\030\t \001"
  "(\006\022\022\n\nsfixed32_f\030\n \001(\017\022\022\n\nsfixed64_f\030\013 \001"
  "(\020\022\017\n\007float_f\030\014 \001(\002\022\020\n\010double_f\030\r \001(\001\022\020\n"
  "\010string_f\030\016 \001(\t\022\017\n\007bytes_f\030\017 \001(\014\022\"\n\010nest"
  "ed_f\030\020 \001(\0132\020.fixtures.Nested\022\032\n\016repeated"
  "_int32\030\021 \003(\005B\002\020\000\022\031\n\rpacked_sint32\030\022 \003(\021B"
  "\002\020\001\"\277\001\n\rAdvancedTypes\022\024\n\nchoice_i32\030\001 \001("
  "\005H\000\022\025\n\013choice_text\030\002 \001(\tH\000\022\032\n\016packed_fix"
  "ed64\030\003 \003(\006B\002\020\001\022\016\n\006chunks\030\004 \003(\014\022\014\n\004flag\030\005"
  " \001(\010\022\014\n\004utf8\030\006 \001(\t\022\014\n\004blob\030\007 \001(\014\022 \n\006nest"
  "ed\030\010 \001(\0132\020.fixtures.NestedB\t\n\007variantb\006p"
  "roto3"
  ;
static ::_pbi::once_flag descriptor_table_fixtures_2fschema_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_fixtures_2fschema_2eproto = {
    false, false, 645, descriptor_table_protodef_fixtures_2fschema_2eproto,
    "fixtures/schema.proto",
    &descriptor_table_fixtures_2fschema_2eproto_once, nullptr, 0, 3,
    schemas, file_default_instances, TableStruct_fixtures_2fschema_2eproto::offsets,
    file_level_metadata_fixtures_2fschema_2eproto, file_level_enum_descriptors_fixtures_2fschema_2eproto,
    file_level_service_descriptors_fixtures_2fschema_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_fixtures_2fschema_2eproto_getter() {
  return &descriptor_table_fixtures_2fschema_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_fixtures_2fschema_2eproto(&descriptor_table_fixtures_2fschema_2eproto);
namespace fixtures {

// ===================================================================

class Nested::_Internal {
 public:
};

Nested::Nested(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:fixtures.Nested)
}
Nested::Nested(const Nested& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  Nested* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.note_){}
    , decltype(_impl_.id_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.note_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.note_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_note().empty()) {
    _this->_impl_.note_.Set(from._internal_note(), 
      _this->GetArenaForAllocation());
  }
  _this->_impl_.id_ = from._impl_.id_;
  // @@protoc_insertion_point(copy_constructor:fixtures.Nested)
}

inline void Nested::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.note_){}
    , decltype(_impl_.id_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.note_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.note_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

Nested::~Nested() {
  // @@protoc_insertion_point(destructor:fixtures.Nested)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void Nested::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.note_.Destroy();
}

void Nested::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void Nested::Clear() {
// @@protoc_insertion_point(message_clear_start:fixtures.Nested)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.note_.ClearToEmpty();
  _impl_.id_ = 0;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* Nested::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // int32 id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // string note = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_note();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "fixtures.Nested.note"));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* Nested::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:fixtures.Nested)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 id = 1;
  if (this->_internal_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(1, this->_internal_id(), target);
  }

  // string note = 2;
  if (!this->_internal_note().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_note().data(), static_cast<int>(this->_internal_note().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "fixtures.Nested.note");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_note(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:fixtures.Nested)
  return target;
}

size_t Nested::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:fixtures.Nested)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string note = 2;
  if (!this->_internal_note().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_note());
  }

  // int32 id = 1;
  if (this->_internal_id() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_id());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData Nested::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    Nested::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*Nested::GetClassData() const { return &_class_data_; }


void Nested::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<Nested*>(&to_msg);
  auto& from = static_cast<const Nested&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:fixtures.Nested)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_note().empty()) {
    _this->_internal_set_note(from._internal_note());
  }
  if (from._internal_id() != 0) {
    _this->_internal_set_id(from._internal_id());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void Nested::CopyFrom(const Nested& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:fixtures.Nested)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Nested::IsInitialized() const {
  return true;
}

void Nested::InternalSwap(Nested* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.note_, lhs_arena,
      &other->_impl_.note_, rhs_arena
  );
  swap(_impl_.id_, other->_impl_.id_);
}

::PROTOBUF_NAMESPACE_ID::Metadata Nested::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_fixtures_2fschema_2eproto_getter, &descriptor_table_fixtures_2fschema_2eproto_once,
      file_level_metadata_fixtures_2fschema_2eproto[0]);
}

// ===================================================================

class AllTypes::_Internal {
 public:
  static const ::fixtures::Nested& nested_f(const AllTypes* msg);
};

const ::fixtures::Nested&
AllTypes::_Internal::nested_f(const AllTypes* msg) {
  return *msg->_impl_.nested_f_;
}
AllTypes::AllTypes(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:fixtures.AllTypes)
}
AllTypes::AllTypes(const AllTypes& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  AllTypes* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.repeated_int32_){from._impl_.repeated_int32_}
    , decltype(_impl_.packed_sint32_){from._impl_.packed_sint32_}
    , /*decltype(_impl_._packed_sint32_cached_byte_size_)*/{0}
    , decltype(_impl_.string_f_){}
    , decltype(_impl_.bytes_f_){}
    , decltype(_impl_.nested_f_){nullptr}
    , decltype(_impl_.int64_f_){}
    , decltype(_impl_.int32_f_){}
    , decltype(_impl_.uint32_f_){}
    , decltype(_impl_.uint64_f_){}
    , decltype(_impl_.sint64_f_){}
    , decltype(_impl_.sint32_f_){}
    , decltype(_impl_.bool_f_){}
    , decltype(_impl_.fixed64_f_){}
    , decltype(_impl_.fixed32_f_){}
    , decltype(_impl_.sfixed32_f_){}
    , decltype(_impl_.sfixed64_f_){}
    , decltype(_impl_.double_f_){}
    , decltype(_impl_.float_f_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.string_f_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.string_f_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_string_f().empty()) {
    _this->_impl_.string_f_.Set(from._internal_string_f(), 
      _this->GetArenaForAllocation());
  }
  _impl_.bytes_f_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.bytes_f_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_bytes_f().empty()) {
    _this->_impl_.bytes_f_.Set(from._internal_bytes_f(), 
      _this->GetArenaForAllocation());
  }
  if (from._internal_has_nested_f()) {
    _this->_impl_.nested_f_ = new ::fixtures::Nested(*from._impl_.nested_f_);
  }
  ::memcpy(&_impl_.int64_f_, &from._impl_.int64_f_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.float_f_) -
    reinterpret_cast<char*>(&_impl_.int64_f_)) + sizeof(_impl_.float_f_));
  // @@protoc_insertion_point(copy_constructor:fixtures.AllTypes)
}

inline void AllTypes::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.repeated_int32_){arena}
    , decltype(_impl_.packed_sint32_){arena}
    , /*decltype(_impl_._packed_sint32_cached_byte_size_)*/{0}
    , decltype(_impl_.string_f_){}
    , decltype(_impl_.bytes_f_){}
    , decltype(_impl_.nested_f_){nullptr}
    , decltype(_impl_.int64_f_){int64_t{0}}
    , decltype(_impl_.int32_f_){0}
    , decltype(_impl_.uint32_f_){0u}
    , decltype(_impl_.uint64_f_){uint64_t{0u}}
    , decltype(_impl_.sint64_f_){int64_t{0}}
    , decltype(_impl_.sint32_f_){0}
    , decltype(_impl_.bool_f_){false}
    , decltype(_impl_.fixed64_f_){uint64_t{0u}}
    , decltype(_impl_.fixed32_f_){0u}
    , decltype(_impl_.sfixed32_f_){0}
    , decltype(_impl_.sfixed64_f_){int64_t{0}}
    , decltype(_impl_.double_f_){0}
    , decltype(_impl_.float_f_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.string_f_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.string_f_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.bytes_f_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.bytes_f_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

AllTypes::~AllTypes() {
  // @@protoc_insertion_point(destructor:fixtures.AllTypes)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void AllTypes::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.repeated_int32_.~RepeatedField();
  _impl_.packed_sint32_.~RepeatedField();
  _impl_.string_f_.Destroy();
  _impl_.bytes_f_.Destroy();
  if (this != internal_default_instance()) delete _impl_.nested_f_;
}

void AllTypes::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void AllTypes::Clear() {
// @@protoc_insertion_point(message_clear_start:fixtures.AllTypes)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.repeated_int32_.Clear();
  _impl_.packed_sint32_.Clear();
  _impl_.string_f_.ClearToEmpty();
  _impl_.bytes_f_.ClearToEmpty();
  if (GetArenaForAllocation() == nullptr && _impl_.nested_f_ != nullptr) {
    delete _impl_.nested_f_;
  }
  _impl_.nested_f_ = nullptr;
  ::memset(&_impl_.int64_f_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.float_f_) -
      reinterpret_cast<char*>(&_impl_.int64_f_)) + sizeof(_impl_.float_f_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* AllTypes::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // int32 int32_f = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.int32_f_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int64 int64_f = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.int64_f_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint32 uint32_f = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          _impl_.uint32_f_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint64 uint64_f = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 32)) {
          _impl_.uint64_f_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // sint32 sint32_f = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 40)) {
          _impl_.sint32_f_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarintZigZag32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // sint64 sint64_f = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 48)) {
          _impl_.sint64_f_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarintZigZag64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // bool bool_f = 7;
      case 7:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 56)) {
          _impl_.bool_f_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // fixed32 fixed32_f = 8;
      case 8:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 69)) {
          _impl_.fixed32_f_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<uint32_t>(ptr);
          ptr += sizeof(uint32_t);
        } else
          goto handle_unusual;
        continue;
      // fixed64 fixed64_f = 9;
      case 9:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 73)) {
          _impl_.fixed64_f_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<uint64_t>(ptr);
          ptr += sizeof(uint64_t);
        } else
          goto handle_unusual;
        continue;
      // sfixed32 sfixed32_f = 10;
      case 10:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 85)) {
          _impl_.sfixed32_f_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<int32_t>(ptr);
          ptr += sizeof(int32_t);
        } else
          goto handle_unusual;
        continue;
      // sfixed64 sfixed64_f = 11;
      case 11:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 89)) {
          _impl_.sfixed64_f_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<int64_t>(ptr);
          ptr += sizeof(int64_t);
        } else
          goto handle_unusual;
        continue;
      // float float_f = 12;
      case 12:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 101)) {
          _impl_.float_f_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else
          goto handle_unusual;
        continue;
      // double double_f = 13;
      case 13:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 105)) {
          _impl_.double_f_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else
          goto handle_unusual;
        continue;
      // string string_f = 14;
      case 14:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 114)) {
          auto str = _internal_mutable_string_f();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "fixtures.AllTypes.string_f"));
        } else
          goto handle_unusual;
        continue;
      // bytes bytes_f = 15;
      case 15:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 122)) {
          auto str = _internal_mutable_bytes_f();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .fixtures.Nested nested_f = 16;
      case 16:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 130)) {
          ptr = ctx->ParseMessage(_internal_mutable_nested_f(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // repeated int32 repeated_int32 = 17 [packed = false];
      case 17:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 136)) {
          ptr -= 2;
          do {
            ptr += 2;
            _internal_add_repeated_int32(::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr));
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<136>(ptr));
        } else if (static_cast<uint8_t>(tag) == 138) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedInt32Parser(_internal_mutable_repeated_int32(), ptr, ctx);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // repeated sint32 packed_sint32 = 18 [packed = true];
      case 18:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 146)) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedSInt32Parser(_internal_mutable_packed_sint32(), ptr, ctx);
          CHK_(ptr);
        } else if (static_cast<uint8_t>(tag) == 144) {
          _internal_add_packed_sint32(::PROTOBUF_NAMESPACE_ID::internal::ReadVarintZigZag32(&ptr));
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* AllTypes::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:fixtures.AllTypes)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 int32_f = 1;
  if (this->_internal_int32_f() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(1, this->_internal_int32_f(), target);
  }

  // int64 int64_f = 2;
  if (this->_internal_int64_f() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt64ToArray(2, this->_internal_int64_f(), target);
  }

  // uint32 uint32_f = 3;
  if (this->_internal_uint32_f() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(3, this->_internal_uint32_f(), target);
  }

  // uint64 uint64_f = 4;
  if (this->_internal_uint64_f() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(4, this->_internal_uint64_f(), target);
  }

  // sint32 sint32_f = 5;
  if (this->_internal_sint32_f() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteSInt32ToArray(5, this->_internal_sint32_f(), target);
  }

  // sint64 sint64_f = 6;
  if (this->_internal_sint64_f() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteSInt64ToArray(6, this->_internal_sint64_f(), target);
  }

  // bool bool_f = 7;
  if (this->_internal_bool_f() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(7, this->_internal_bool_f(), target);
  }

  // fixed32 fixed32_f = 8;
  if (this->_internal_fixed32_f() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFixed32ToArray(8, this->_internal_fixed32_f(), target);
  }

  // fixed64 fixed64_f = 9;
  if (this->_internal_fixed64_f() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFixed64ToArray(9, this->_internal_fixed64_f(), target);
  }

  // sfixed32 sfixed32_f = 10;
  if (this->_internal_sfixed32_f() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteSFixed32ToArray(10, this->_internal_sfixed32_f(), target);
  }

  // sfixed64 sfixed64_f = 11;
  if (this->_internal_sfixed64_f() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteSFixed64ToArray(11, this->_internal_sfixed64_f(), target);
  }

  // float float_f = 12;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_float_f = this->_internal_float_f();
  uint32_t raw_float_f;
  memcpy(&raw_float_f, &tmp_float_f, sizeof(tmp_float_f));
  if (raw_float_f != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(12, this->_internal_float_f(), target);
  }

  // double double_f = 13;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_double_f = this->_internal_double_f();
  uint64_t raw_double_f;
  memcpy(&raw_double_f, &tmp_double_f, sizeof(tmp_double_f));
  if (raw_double_f != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(13, this->_internal_double_f(), target);
  }

  // string string_f = 14;
  if (!this->_internal_string_f().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_string_f().data(), static_cast<int>(this->_internal_string_f().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "fixtures.AllTypes.string_f");
    target = stream->WriteStringMaybeAliased(
        14, this->_internal_string_f(), target);
  }

  // bytes bytes_f = 15;
  if (!this->_internal_bytes_f().empty()) {
    target = stream->WriteBytesMaybeAliased(
        15, this->_internal_bytes_f(), target);
  }

  // .fixtures.Nested nested_f = 16;
  if (this->_internal_has_nested_f()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(16, _Internal::nested_f(this),
        _Internal::nested_f(this).GetCachedSize(), target, stream);
  }

  // repeated int32 repeated_int32 = 17 [packed = false];
  for (int i = 0, n = this->_internal_repeated_int32_size(); i < n; i++) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(17, this->_internal_repeated_int32(i), target);
  }

  // repeated sint32 packed_sint32 = 18 [packed = true];
  {
    int byte_size = _impl_._packed_sint32_cached_byte_size_.load(std::memory_order_relaxed);
    if (byte_size > 0) {
      target = stream->WriteSInt32Packed(
          18, _internal_packed_sint32(), byte_size, target);
    }
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:fixtures.AllTypes)
  return target;
}

size_t AllTypes::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:fixtures.AllTypes)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated int32 repeated_int32 = 17 [packed = false];
  {
    size_t data_size = ::_pbi::WireFormatLite::
      Int32Size(this->_impl_.repeated_int32_);
    total_size += 2 *
                  ::_pbi::FromIntSize(this->_internal_repeated_int32_size());
    total_size += data_size;
  }

  // repeated sint32 packed_sint32 = 18 [packed = true];
  {
    size_t data_size = ::_pbi::WireFormatLite::
      SInt32Size(this->_impl_.packed_sint32_);
    if (data_size > 0) {
      total_size += 2 +
        ::_pbi::WireFormatLite::Int32Size(static_cast<int32_t>(data_size));
    }
    int cached_size = ::_pbi::ToCachedSize(data_size);
    _impl_._packed_sint32_cached_byte_size_.store(cached_size,
                                    std::memory_order_relaxed);
    total_size += data_size;
  }

  // string string_f = 14;
  if (!this->_internal_string_f().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_string_f());
  }

  // bytes bytes_f = 15;
  if (!this->_internal_bytes_f().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
        this->_internal_bytes_f());
  }

  // .fixtures.Nested nested_f = 16;
  if (this->_internal_has_nested_f()) {
    total_size += 2 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.nested_f_);
  }

  // int64 int64_f = 2;
  if (this->_internal_int64_f() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(this->_internal_int64_f());
  }

  // int32 int32_f = 1;
  if (this->_internal_int32_f() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_int32_f());
  }

  // uint32 uint32_f = 3;
  if (this->_internal_uint32_f() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_uint32_f());
  }

  // uint64 uint64_f = 4;
  if (this->_internal_uint64_f() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(this->_internal_uint64_f());
  }

  // sint64 sint64_f = 6;
  if (this->_internal_sint64_f() != 0) {
    total_size += ::_pbi::WireFormatLite::SInt64SizePlusOne(this->_internal_sint64_f());
  }

  // sint32 sint32_f = 5;
  if (this->_internal_sint32_f() != 0) {
    total_size += ::_pbi::WireFormatLite::SInt32SizePlusOne(this->_internal_sint32_f());
  }

  // bool bool_f = 7;
  if (this->_internal_bool_f() != 0) {
    total_size += 1 + 1;
  }

  // fixed64 fixed64_f = 9;
  if (this->_internal_fixed64_f() != 0) {
    total_size += 1 + 8;
  }

  // fixed32 fixed32_f = 8;
  if (this->_internal_fixed32_f() != 0) {
    total_size += 1 + 4;
  }

  // sfixed32 sfixed32_f = 10;
  if (this->_internal_sfixed32_f() != 0) {
    total_size += 1 + 4;
  }

  // sfixed64 sfixed64_f = 11;
  if (this->_internal_sfixed64_f() != 0) {
    total_size += 1 + 8;
  }

  // double double_f = 13;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_double_f = this->_internal_double_f();
  uint64_t raw_double_f;
  memcpy(&raw_double_f, &tmp_double_f, sizeof(tmp_double_f));
  if (raw_double_f != 0) {
    total_size += 1 + 8;
  }

  // float float_f = 12;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_float_f = this->_internal_float_f();
  uint32_t raw_float_f;
  memcpy(&raw_float_f, &tmp_float_f, sizeof(tmp_float_f));
  if (raw_float_f != 0) {
    total_size += 1 + 4;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData AllTypes::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    AllTypes::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*AllTypes::GetClassData() const { return &_class_data_; }


void AllTypes::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<AllTypes*>(&to_msg);
  auto& from = static_cast<const AllTypes&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:fixtures.AllTypes)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.repeated_int32_.MergeFrom(from._impl_.repeated_int32_);
  _this->_impl_.packed_sint32_.MergeFrom(from._impl_.packed_sint32_);
  if (!from._internal_string_f().empty()) {
    _this->_internal_set_string_f(from._internal_string_f());
  }
  if (!from._internal_bytes_f().empty()) {
    _this->_internal_set_bytes_f(from._internal_bytes_f());
  }
  if (from._internal_has_nested_f()) {
    _this->_internal_mutable_nested_f()->::fixtures::Nested::MergeFrom(
        from._internal_nested_f());
  }
  if (from._internal_int64_f() != 0) {
    _this->_internal_set_int64_f(from._internal_int64_f());
  }
  if (from._internal_int32_f() != 0) {
    _this->_internal_set_int32_f(from._internal_int32_f());
  }
  if (from._internal_uint32_f() != 0) {
    _this->_internal_set_uint32_f(from._internal_uint32_f());
  }
  if (from._internal_uint64_f() != 0) {
    _this->_internal_set_uint64_f(from._internal_uint64_f());
  }
  if (from._internal_sint64_f() != 0) {
    _this->_internal_set_sint64_f(from._internal_sint64_f());
  }
  if (from._internal_sint32_f() != 0) {
    _this->_internal_set_sint32_f(from._internal_sint32_f());
  }
  if (from._internal_bool_f() != 0) {
    _this->_internal_set_bool_f(from._internal_bool_f());
  }
  if (from._internal_fixed64_f() != 0) {
    _this->_internal_set_fixed64_f(from._internal_fixed64_f());
  }
  if (from._internal_fixed32_f() != 0) {
    _this->_internal_set_fixed32_f(from._internal_fixed32_f());
  }
  if (from._internal_sfixed32_f() != 0) {
    _this->_internal_set_sfixed32_f(from._internal_sfixed32_f());
  }
  if (from._internal_sfixed64_f() != 0) {
    _this->_internal_set_sfixed64_f(from._internal_sfixed64_f());
  }
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_double_f = from._internal_double_f();
  uint64_t raw_double_f;
  memcpy(&raw_double_f, &tmp_double_f, sizeof(tmp_double_f));
  if (raw_double_f != 0) {
    _this->_internal_set_double_f(from._internal_double_f());
  }
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_float_f = from._internal_float_f();
  uint32_t raw_float_f;
  memcpy(&raw_float_f, &tmp_float_f, sizeof(tmp_float_f));
  if (raw_float_f != 0) {
    _this->_internal_set_float_f(from._internal_float_f());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void AllTypes::CopyFrom(const AllTypes& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:fixtures.AllTypes)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool AllTypes::IsInitialized() const {
  return true;
}

void AllTypes::InternalSwap(AllTypes* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.repeated_int32_.InternalSwap(&other->_impl_.repeated_int32_);
  _impl_.packed_sint32_.InternalSwap(&other->_impl_.packed_sint32_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.string_f_, lhs_arena,
      &other->_impl_.string_f_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.bytes_f_, lhs_arena,
      &other->_impl_.bytes_f_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(AllTypes, _impl_.float_f_)
      + sizeof(AllTypes::_impl_.float_f_)
      - PROTOBUF_FIELD_OFFSET(AllTypes, _impl_.nested_f_)>(
          reinterpret_cast<char*>(&_impl_.nested_f_),
          reinterpret_cast<char*>(&other->_impl_.nested_f_));
}

::PROTOBUF_NAMESPACE_ID::Metadata AllTypes::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_fixtures_2fschema_2eproto_getter, &descriptor_table_fixtures_2fschema_2eproto_once,
      file_level_metadata_fixtures_2fschema_2eproto[1]);
}

// ===================================================================

class AdvancedTypes::_Internal {
 public:
  static const ::fixtures::Nested& nested(const AdvancedTypes* msg);
};

const ::fixtures::Nested&
AdvancedTypes::_Internal::nested(const AdvancedTypes* msg) {
  return *msg->_impl_.nested_;
}
AdvancedTypes::AdvancedTypes(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:fixtures.AdvancedTypes)
}
AdvancedTypes::AdvancedTypes(const AdvancedTypes& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  AdvancedTypes* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.packed_fixed64_){from._impl_.packed_fixed64_}
    , decltype(_impl_.chunks_){from._impl_.chunks_}
    , decltype(_impl_.utf8_){}
    , decltype(_impl_.blob_){}
    , decltype(_impl_.nested_){nullptr}
    , decltype(_impl_.flag_){}
    , decltype(_impl_.variant_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , /*decltype(_impl_._oneof_case_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.utf8_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.utf8_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_utf8().empty()) {
    _this->_impl_.utf8_.Set(from._internal_utf8(), 
      _this->GetArenaForAllocation());
  }
  _impl_.blob_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.blob_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_blob().empty()) {
    _this->_impl_.blob_.Set(from._internal_blob(), 
      _this->GetArenaForAllocation());
  }
  if (from._internal_has_nested()) {
    _this->_impl_.nested_ = new ::fixtures::Nested(*from._impl_.nested_);
  }
  _this->_impl_.flag_ = from._impl_.flag_;
  clear_has_variant();
  switch (from.variant_case()) {
    case kChoiceI32: {
      _this->_internal_set_choice_i32(from._internal_choice_i32());
      break;
    }
    case kChoiceText: {
      _this->_internal_set_choice_text(from._internal_choice_text());
      break;
    }
    case VARIANT_NOT_SET: {
      break;
    }
  }
  // @@protoc_insertion_point(copy_constructor:fixtures.AdvancedTypes)
}

inline void AdvancedTypes::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.packed_fixed64_){arena}
    , decltype(_impl_.chunks_){arena}
    , decltype(_impl_.utf8_){}
    , decltype(_impl_.blob_){}
    , decltype(_impl_.nested_){nullptr}
    , decltype(_impl_.flag_){false}
    , decltype(_impl_.variant_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , /*decltype(_impl_._oneof_case_)*/{}
  };
  _impl_.utf8_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.utf8_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.blob_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.blob_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  clear_has_variant();
}

AdvancedTypes::~AdvancedTypes() {
  // @@protoc_insertion_point(destructor:fixtures.AdvancedTypes)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void AdvancedTypes::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.packed_fixed64_.~RepeatedField();
  _impl_.chunks_.~RepeatedPtrField();
  _impl_.utf8_.Destroy();
  _impl_.blob_.Destroy();
  if (this != internal_default_instance()) delete _impl_.nested_;
  if (has_variant()) {
    clear_variant();
  }
}

void AdvancedTypes::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void AdvancedTypes::clear_variant() {
// @@protoc_insertion_point(one_of_clear_start:fixtures.AdvancedTypes)
  switch (variant_case()) {
    case kChoiceI32: {
      // No need to clear
      break;
    }
    case kChoiceText: {
      _impl_.variant_.choice_text_.Destroy();
      break;
    }
    case VARIANT_NOT_SET: {
      break;
    }
  }
  _impl_._oneof_case_[0] = VARIANT_NOT_SET;
}


void AdvancedTypes::Clear() {
// @@protoc_insertion_point(message_clear_start:fixtures.AdvancedTypes)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.packed_fixed64_.Clear();
  _impl_.chunks_.Clear();
  _impl_.utf8_.ClearToEmpty();
  _impl_.blob_.ClearToEmpty();
  if (GetArenaForAllocation() == nullptr && _impl_.nested_ != nullptr) {
    delete _impl_.nested_;
  }
  _impl_.nested_ = nullptr;
  _impl_.flag_ = false;
  clear_variant();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* AdvancedTypes::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // int32 choice_i32 = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _internal_set_choice_i32(::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr));
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // string choice_text = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_choice_text();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "fixtures.AdvancedTypes.choice_text"));
        } else
          goto handle_unusual;
        continue;
      // repeated fixed64 packed_fixed64 = 3 [packed = true];
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedFixed64Parser(_internal_mutable_packed_fixed64(), ptr, ctx);
          CHK_(ptr);
        } else if (static_cast<uint8_t>(tag) == 25) {
          _internal_add_packed_fixed64(::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<uint64_t>(ptr));
          ptr += sizeof(uint64_t);
        } else
          goto handle_unusual;
        continue;
      // repeated bytes chunks = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 34)) {
          ptr -= 1;
          do {
            ptr += 1;
            auto str = _internal_add_chunks();
            ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<34>(ptr));
        } else
          goto handle_unusual;
        continue;
      // bool flag = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 40)) {
          _impl_.flag_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // string utf8 = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 50)) {
          auto str = _internal_mutable_utf8();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "fixtures.AdvancedTypes.utf8"));
        } else
          goto handle_unusual;
        continue;
      // bytes blob = 7;
      case 7:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 58)) {
          auto str = _internal_mutable_blob();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .fixtures.Nested nested = 8;
      case 8:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 66)) {
          ptr = ctx->ParseMessage(_internal_mutable_nested(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* AdvancedTypes::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:fixtures.AdvancedTypes)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 choice_i32 = 1;
  if (_internal_has_choice_i32()) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(1, this->_internal_choice_i32(), target);
  }

  // string choice_text = 2;
  if (_internal_has_choice_text()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_choice_text().data(), static_cast<int>(this->_internal_choice_text().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "fixtures.AdvancedTypes.choice_text");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_choice_text(), target);
  }

  // repeated fixed64 packed_fixed64 = 3 [packed = true];
  if (this->_internal_packed_fixed64_size() > 0) {
    target = stream->WriteFixedPacked(3, _internal_packed_fixed64(), target);
  }

  // repeated bytes chunks = 4;
  for (int i = 0, n = this->_internal_chunks_size(); i < n; i++) {
    const auto& s = this->_internal_chunks(i);
    target = stream->WriteBytes(4, s, target);
  }

  // bool flag = 5;
  if (this->_internal_flag() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(5, this->_internal_flag(), target);
  }

  // string utf8 = 6;
  if (!this->_internal_utf8().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_utf8().data(), static_cast<int>(this->_internal_utf8().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "fixtures.AdvancedTypes.utf8");
    target = stream->WriteStringMaybeAliased(
        6, this->_internal_utf8(), target);
  }

  // bytes blob = 7;
  if (!this->_internal_blob().empty()) {
    target = stream->WriteBytesMaybeAliased(
        7, this->_internal_blob(), target);
  }

  // .fixtures.Nested nested = 8;
  if (this->_internal_has_nested()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(8, _Internal::nested(this),
        _Internal::nested(this).GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:fixtures.AdvancedTypes)
  return target;
}

size_t AdvancedTypes::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:fixtures.AdvancedTypes)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated fixed64 packed_fixed64 = 3 [packed = true];
  {
    unsigned int count = static_cast<unsigned int>(this->_internal_packed_fixed64_size());
    size_t data_size = 8UL * count;
    if (data_size > 0) {
      total_size += 1 +
        ::_pbi::WireFormatLite::Int32Size(static_cast<int32_t>(data_size));
    }
    total_size += data_size;
  }

  // repeated bytes chunks = 4;
  total_size += 1 *
      ::PROTOBUF_NAMESPACE_ID::internal::FromIntSize(_impl_.chunks_.size());
  for (int i = 0, n = _impl_.chunks_.size(); i < n; i++) {
    total_size += ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
      _impl_.chunks_.Get(i));
  }

  // string utf8 = 6;
  if (!this->_internal_utf8().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_utf8());
  }

  // bytes blob = 7;
  if (!this->_internal_blob().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
        this->_internal_blob());
  }

  // .fixtures.Nested nested = 8;
  if (this->_internal_has_nested()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.nested_);
  }

  // bool flag = 5;
  if (this->_internal_flag() != 0) {
    total_size += 1 + 1;
  }

  switch (variant_case()) {
    // int32 choice_i32 = 1;
    case kChoiceI32: {
      total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_choice_i32());
      break;
    }
    // string choice_text = 2;
    case kChoiceText: {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
          this->_internal_choice_text());
      break;
    }
    case VARIANT_NOT_SET: {
      break;
    }
  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData AdvancedTypes::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    AdvancedTypes::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*AdvancedTypes::GetClassData() const { return &_class_data_; }


void AdvancedTypes::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<AdvancedTypes*>(&to_msg);
  auto& from = static_cast<const AdvancedTypes&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:fixtures.AdvancedTypes)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.packed_fixed64_.MergeFrom(from._impl_.packed_fixed64_);
  _this->_impl_.chunks_.MergeFrom(from._impl_.chunks_);
  if (!from._internal_utf8().empty()) {
    _this->_internal_set_utf8(from._internal_utf8());
  }
  if (!from._internal_blob().empty()) {
    _this->_internal_set_blob(from._internal_blob());
  }
  if (from._internal_has_nested()) {
    _this->_internal_mutable_nested()->::fixtures::Nested::MergeFrom(
        from._internal_nested());
  }
  if (from._internal_flag() != 0) {
    _this->_internal_set_flag(from._internal_flag());
  }
  switch (from.variant_case()) {
    case kChoiceI32: {
      _this->_internal_set_choice_i32(from._internal_choice_i32());
      break;
    }
    case kChoiceText: {
      _this->_internal_set_choice_text(from._internal_choice_text());
      break;
    }
    case VARIANT_NOT_SET: {
      break;
    }
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void AdvancedTypes::CopyFrom(const AdvancedTypes& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:fixtures.AdvancedTypes)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool AdvancedTypes::IsInitialized() const {
  return true;
}

void AdvancedTypes::InternalSwap(AdvancedTypes* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.packed_fixed64_.InternalSwap(&other->_impl_.packed_fixed64_);
  _impl_.chunks_.InternalSwap(&other->_impl_.chunks_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.utf8_, lhs_arena,
      &other->_impl_.utf8_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.blob_, lhs_arena,
      &other->_impl_.blob_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(AdvancedTypes, _impl_.flag_)
      + sizeof(AdvancedTypes::_impl_.flag_)
      - PROTOBUF_FIELD_OFFSET(AdvancedTypes, _impl_.nested_)>(
          reinterpret_cast<char*>(&_impl_.nested_),
          reinterpret_cast<char*>(&other->_impl_.nested_));
  swap(_impl_.variant_, other->_impl_.variant_);
  swap(_impl_._oneof_case_[0], other->_impl_._oneof_case_[0]);
}

::PROTOBUF_NAMESPACE_ID::Metadata AdvancedTypes::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_fixtures_2fschema_2eproto_getter, &descriptor_table_fixtures_2fschema_2eproto_once,
      file_level_metadata_fixtures_2fschema_2eproto[2]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace fixtures
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::fixtures::Nested*
Arena::CreateMaybeMessage< ::fixtures::Nested >(Arena* arena) {
  return Arena::CreateMessageInternal< ::fixtures::Nested >(arena);
}
template<> PROTOBUF_NOINLINE ::fixtures::AllTypes*
Arena::CreateMaybeMessage< ::fixtures::AllTypes >(Arena* arena) {
  return Arena::CreateMessageInternal< ::fixtures::AllTypes >(arena);
}
template<> PROTOBUF_NOINLINE ::fixtures::AdvancedTypes*
Arena::CreateMaybeMessage< ::fixtures::AdvancedTypes >(Arena* arena) {
  return Arena::CreateMessageInternal< ::fixtures::AdvancedTypes >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
